# Generated by Django 5.2.5 on 2025-08-25 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(default='DE00 0000 0000 0000 0000 00', max_length=32)),
                ('balance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
            ],
        ),
    ]
