# Generated by Django 5.2.5 on 2025-08-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bic',
            field=models.CharField(default='xxxxxxxxxxx', max_length=11),
        ),
    ]
