# Generated by Django 5.2.5 on 2025-09-04 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_bic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('sub_acc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(default='DE00 0000 0000 0000 0000 00', max_length=32)),
                ('super_acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
