# Generated by Django 5.2.5 on 2025-08-26 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0004_delete_budgettransaction_budget_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('tx_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('tx_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.budget')),
            ],
        ),
    ]
