# Generated by Django 5.2.5 on 2025-08-24 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('occured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(default='money goes brrrr', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='current_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default='Main Budget', max_length=64),
        ),
    ]
