# Generated by Django 5.2.5 on 2025-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budgettransaction_alter_budget_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='target_balance',
            field=models.DecimalField(decimal_places=6, max_digits=24, null=True),
        ),
    ]
