# Generated by Django 5.2.5 on 2025-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_target_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetTransaction',
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
