# Generated by Django 5.2.5 on 2025-08-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_delete_budgettransaction_budget_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='savings_rate',
            field=models.DecimalField(decimal_places=6, max_digits=18, null=True),
        ),
    ]
